name: Build and publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install packages
        run: |
          npm install -g yarn
          yarn install
      - name: Build JavaScript
        run: yarn run build
      - name: Build Docker image
        run: docker build . --tag docker.pkg.github.com/minna-technologies/eslint:master
      - name: Publish Docker image
        run: docker push docker.pkg.github.com/minna-technologies/eslint:master
